spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  header: Authorization
  secret: ZGdhaG4tdHV0b3JpYWwtZGdhaG4tdHV0b3JpYWwtdGRnYWhuLXR1dG9yaWEtZGdhaG4tdHV0b3JpYWwtZGdhaG4tdHV0b3JpYWwtZGdhaG4tdHV0b3JpYWwtZGdhaG4tdHV0b3JpYWwK
  token-validity-in-seconds: 86400