## 회원가입
POST http://localhost:8080/v1/sign-up
Content-Type: application/json

{
  "email": "dgahn@icloud.com",
  "password": "123"
}

###
## 로그인
POST http://localhost:8080/v1/sign-in
Content-Type: application/json

{
  "email": "dgahn@icloud.com",
  "password": "123"
}

> {%
client.global.set("accessToken", response.body.accessToken);
client.global.set("refreshToken", response.body.refreshToken);
%}

###
## 지출 내역 작성
POST http://localhost:8080/v1/expenditures
Authorization: {{accessToken}}
Refresh: {{refreshToken}}
Content-Type: application/json

{
  "email": "dgahn@icloud.com",
  "money": 1000,
  "memo": "메모메모메모메모"
}

###
## 지출 내역 조회
GET http://localhost:8080/v1/expenditures?email=dgahn@icloud.com&page=1&size=10
Authorization: {{accessToken}}
Refresh: {{refreshToken}}

###
## 지출 내역 수정
PUT http://localhost:8080/v1/expenditures/1
Authorization: {{accessToken}}
Refresh: {{refreshToken}}
Content-Type: application/json

{
  "email": "dgahn@icloud.com",
  "money": 1000,
  "memo": "메모메모메모메모11111111111111111111"
}

###
## 지출 내역 삭제
DELETE http://localhost:8080/v1/expenditures/1
Authorization: {{accessToken}}
Refresh: {{refreshToken}}

###
## 지출 내역 복구
PUT http://localhost:8080/v1/expenditures/1/recovery
Authorization: {{accessToken}}
Refresh: {{refreshToken}}

###
## 로그 아웃

POST http://localhost:8080/v1/sign-out
Authorization: {{accessToken}}
Refresh: {{refreshToken}}
Content-Type: application/json

{
  "email": "dgahn@icloud.com"
}