## 회원가입
POST http://localhost:8080/v1/sign-up
Content-Type: application/json

{
  "email": "dgahn@icloud.com",
  "password": "123"
}

###
## 로그인
POST http://localhost:8080/v1/sign-in
Content-Type: application/json


{
  "email": "dgahn@icloud.com",
  "password": "123"
}

> {% client.global.set("auth_token", response.body.token); %}